USE VIDRARIAS
GO


--Criando tabela para utilizar dados aleatórios
Drop table MARCA_VIDRARIA
go

CREATE TABLE  MARCA_VIDRARIA(
	IDMARCA INT PRIMARY KEY IDENTITY,
	MARCA VARCHAR(30),
	TIPO VARCHAR(30),
	VOLUME DECIMAL(4)
)
GO

INSERT INTO MARCA_VIDRARIA VALUES('Dinamica', 'Pipeta Volumétrica',5)
INSERT INTO MARCA_VIDRARIA VALUES('Fisatom', 'Balão Volumétrico', 10)
INSERT INTO MARCA_VIDRARIA VALUES('Hanna Instruments', 'Bureta', 25)
INSERT INTO MARCA_VIDRARIA VALUES('HG', 'Proveta', 50)
INSERT INTO MARCA_VIDRARIA VALUES('INCOTERM', 'Béquer', 100)
INSERT INTO MARCA_VIDRARIA VALUES('Kasvi', 'Cálice', 250)
INSERT INTO MARCA_VIDRARIA VALUES('Macherey-Nagel', 'Pipeta Graduada',500)
INSERT INTO MARCA_VIDRARIA VALUES('Marte', 'Kitassato', 1000)
INSERT INTO MARCA_VIDRARIA VALUES('Labor', 'Erlenmeyer', 2000)
INSERT INTO MARCA_VIDRARIA VALUES('Vitral', 'Pipeta Volumétrica', 5)

GO

--TESTANDO PROCEDURE

SELECT MARCA FROM MARCA_VIDRARIA
WHERE IDMARCA = FLOOR (1 + RAND() * (11 - 1))
GO
SELECT TIPO FROM MARCA_VIDRARIA
WHERE IDMARCA = FLOOR (1 + RAND() * (11 - 1))
GO

SELECT VOLUME FROM MARCA_VIDRARIA
WHERE IDMARCA = FLOOR (1 + RAND() * (11 - 1))
GO

SELECT * FROM MARCA_VIDRARIA
WHERE IDMARCA = FLOOR (1 + RAND() * (11 - 1))
GO

SELECT VOLUME * ((987 + RAND()*(1000 - 987))/100) FROM MARCA_VIDRARIA
GO


TRUNCATE TABLE VIDRARIA
GO

--CRIANDO PROCEDURE PARA PRENECHER O BANCO DE DADOS

CREATE PROCEDURE FILL_VIDRARIA AS
DECLARE

			@TIPO_DE_VIDRARIA VARCHAR(30),
			@MARCA VARCHAR(30),
			@VOLUME_NOMINAL NUMERIC(10,4),
			@VOLUME_REAL NUMERIC(10,4)
			
BEGIN

			SET @TIPO_DE_VIDRARIA = (SELECT TIPO FROM MARCA_VIDRARIA
									 WHERE IDMARCA = FLOOR (1 + RAND() * (11 - 1)))
			
					
			SET @MARCA = (SELECT MARCA FROM MARCA_VIDRARIA
						  WHERE IDMARCA = FLOOR (1 + RAND() * (11 - 1)))

			SET @VOLUME_NOMINAL = (SELECT VOLUME FROM MARCA_VIDRARIA
									WHERE IDMARCA = FLOOR (1 + RAND() * (11 - 1)))


			SET @VOLUME_REAL = @VOLUME_NOMINAL*((987 + RAND()*(1000 - 987))/1000)

			INSERT INTO VIDRARIA(TIPO_DE_VIDRARIA, MARCA, VOLUME_NOMINAL, VOLUME_REAL)
			VALUES
			(@TIPO_DE_VIDRARIA,@MARCA, @VOLUME_NOMINAL, @VOLUME_REAL)
END
GO


EXEC FILL_VIDRARIA
GO 1000

SELECT * FROM VIDRARIA
GO


