USE VIDRARIAS
GO

SELECT TOP 10 * FROM CALIBRACAO
GO

--VIEW COMPLETO DOS DADOS DA CALIBRACAO

CREATE VIEW vwREALATORIO_COMPLETO AS
SELECT  V.TIPO_DE_VIDRARIA,
		V.VOLUME_NOMINAL,
		V.IDVIDRARIA AS IDENTIFICACAO,
		C.RESPONSAVEL AS RESPONSAVEL_CALIBRACAO, 
		C.DATA_DA_CALIBRACAO AS DATA_DE_CALIBRACAO,
		C.PRAZO_PROX_CALIBRACAO AS PRAZO_ANOS,
		DATEADD (year,C.PRAZO_PROX_CALIBRACAO, C.DATA_DA_CALIBRACAO) AS DATA_DE_VALIDADE,
		CASE WHEN DATEDIFF (DAY ,GETDATE(), DATEADD(year,C.PRAZO_PROX_CALIBRACAO, C.DATA_DA_CALIBRACAO)) < '0' THEN 'VENCIDO' ELSE'VÁLIDO' END AS INFORMACAO
		FROM VIDRARIA V
		INNER JOIN CALIBRACAO C
		ON V.IDVIDRARIA = C.ID_VIDRARIA
		
GO


--VIEW COMPLETO DAS VALIDADES

CREATE VIEW vwVALIDADE AS
SELECT  DATA_DA_CALIBRACAO,
		DATEADD(year,PRAZO_PROX_CALIBRACAO, DATA_DA_CALIBRACAO) AS VALIDADE,
		CASE WHEN DATEDIFF (DAY ,GETDATE(), 
		DATEADD(year,PRAZO_PROX_CALIBRACAO, DATA_DA_CALIBRACAO)) < '0' 
		THEN 'VENCIDO' ELSE'VÁLIDO' 
		END AS VALIDO
		FROM CALIBRACAO
GO


SELECT  DATEADD(year,PRAZO_PROX_CALIBRACAO, DATA_DA_CALIBRACAO) AS VALIDADE
		FROM CALIBRACAO
GO

--VIEW COMPLETO SE É VALIDO OU NÃO

CREATE VIEW vwQTDVidrariaValida AS
SELECT  (SELECT COUNT(*) FROM vwVALIDADE
		WHERE VALIDO = 'VÁLIDO') AS VIDRARIA_VALIDAS,
		(SELECT COUNT(*) FROM vwVALIDADE
		WHERE VALIDO = 'VENCIDO') AS VIDRARIA_VENCIDOS
GO

SELECT * FROM vwREALATORIO_COMPLETO
GO

SELECT * FROM vwQTDVidrariaValida
GO
