
CREATE TABLE TESTE_DATA(
	IDDIA INT PRIMARY KEY IDENTITY,
	DIAS DATE
)
GO


DECLARE

--DEFININDO VARIAVEIS
@ID_VER INT,
@ID_MAXIMO INT,
@DATA_VALIDADE DATE,
@DATA_VERIFICACAO DATE,
@PRAZO INT,
@HOJE DATE

--ATRIBUINDO VALORES AS VARIAVEIS
SET @ID_VER = 1
SET @ID_MAXIMO = (SELECT MAX(IDENTIFICACAO) FROM vwREALATORIO_COMPLETO)
SET @PRAZO = 6
SET @HOJE = GETDATE()

--UTILIZANDO O LAÇO WHILE PARA INSERIR OS VALORES DE DATA
WHILE @ID_VER <= @ID_MAXIMO
BEGIN
			
			SET @DATA_VERIFICACAO = (SELECT DATA_DE_CALIBRACAO FROM vwREALATORIO_COMPLETO
									WHERE IDENTIFICACAO = @ID_VER)
			SET @DATA_VALIDADE = (SELECT DATA_DE_VALIDADE FROM vwREALATORIO_COMPLETO
								  WHERE IDENTIFICACAO = @ID_VER)
			

			WHILE @DATA_VERIFICACAO < @DATA_VALIDADE
					BEGIN
					INSERT INTO TESTE_DATA(DIAS) VALUES (@DATA_VERIFICACAO)
					SET @DATA_VERIFICACAO = DATEADD(MONTH, @PRAZO,@DATA_VERIFICACAO)
					IF @DATA_VERIFICACAO > @DATA_VALIDADE BREAK --DEFININDO LIMITE DE DATA SE A VIDRARIA ESTIVER VENCIDA
					IF @DATA_VERIFICACAO < @HOJE --DEFININDO LIMITE SE A VIDRARIA AINDA NÃO VENCEU
					INSERT INTO TESTE_DATA(DIAS) VALUES (@DATA_VERIFICACAO)
					SET @DATA_VERIFICACAO = DATEADD(MONTH, @PRAZO,@DATA_VERIFICACAO)
					IF @DATA_VERIFICACAO > @HOJE BREAK --LIMITE PARA HOJE POIS A VIDRARIA NÃO TERA REGISTROS DE VERIFICAÇÃO SE ELA AINDA NÃO VENCEU
					END



			SET @ID_VER = @ID_VER + 1 
				 

END
GO 


SELECT DATA_DE_CALIBRACAO, DATA_DE_VALIDADE FROM vwREALATORIO_COMPLETO
WHERE IDENTIFICACAO = 2
GO

SELECT * FROM  TESTE_DATA
GO
TRUNCATE TABLE TESTE_DATA
